name: deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Node 18
        uses: actions/setup-node@v1
        with:
          node-version: 18
      - name: install
        run: |
          yarn
      - name: build
        run: |
          yarn build
      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./packages/app/build
